
# ========= Border =========
file_panel_border = '#d6dcdb'
sidebar_border = '#d6dcdb'
footer_border = '#d6dcdb'

# ========= Border Active =========
file_panel_border_active = '#85abbc'
sidebar_border_active = '#85abbc'
footer_border_active = '#85abbc'
modal_border_active = '#85abbc'

# ========= Background (bg) =========
full_screen_bg = '#232829'
file_panel_bg = '#232829'
sidebar_bg = '#232829'
footer_bg = '#232829'
modal_bg = '#232829'

# ========= Foreground (fg) =========
full_screen_fg = '#dcd6d6'
file_panel_fg = '#dcd6d6'
sidebar_fg = '#dcd6d6'
footer_fg = '#dcd6d6'
modal_fg = '#dcd6d6'

# ========= Special Color =========
cursor = '#dcd6d6'
correct = '#98b3a3'
error = '#b39a98'
hint = '#98b3b3'
cancel = '#b39a98'
gradient_color = ['#232829', "#788587"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#232829'
file_panel_top_path = '#788587'
file_panel_item_selected_fg = '#788587'
file_panel_item_selected_bg = '#232829'

# ========= Sidebar Special Items =========
sidebar_title = '#dcd6d6'
sidebar_item_selected_fg = '#788587'
sidebar_item_selected_bg = '#232829'
sidebar_divider = '#d6dcdb'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#b39a98'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#98b3a3'
